/**
 * generated by Xtext 2.32.0
 */
package springboot.automate.grabDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link springboot.automate.grabDsl.ClassDefinition#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.ClassDefinition#getName <em>Name</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.ClassDefinition#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see springboot.automate.grabDsl.GrabDslPackage#getClassDefinition()
 * @model
 * @generated
 */
public interface ClassDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link springboot.automate.grabDsl.Annotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see springboot.automate.grabDsl.GrabDslPackage#getClassDefinition_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<Annotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getClassDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.ClassDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link springboot.automate.grabDsl.MemberDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see springboot.automate.grabDsl.GrabDslPackage#getClassDefinition_Members()
   * @model containment="true"
   * @generated
   */
  EList<MemberDefinition> getMembers();

} // ClassDefinition
