/**
 * generated by Xtext 2.32.0
 */
package springboot.automate.grabDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link springboot.automate.grabDsl.EntityType#getEntity <em>Entity</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.EntityType#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see springboot.automate.grabDsl.GrabDslPackage#getEntityType()
 * @model
 * @generated
 */
public interface EntityType extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' attribute.
   * @see #setEntity(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getEntityType_Entity()
   * @model
   * @generated
   */
  String getEntity();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.EntityType#getEntity <em>Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' attribute.
   * @see #getEntity()
   * @generated
   */
  void setEntity(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getEntityType_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.EntityType#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

} // EntityType
