/**
 * generated by Xtext 2.32.0
 */
package springboot.automate.grabDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see springboot.automate.grabDsl.GrabDslFactory
 * @model kind="package"
 * @generated
 */
public interface GrabDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "grabDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.automate.springboot/GrabDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "grabDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GrabDslPackage eINSTANCE = springboot.automate.grabDsl.impl.GrabDslPackageImpl.init();

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.ModelImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Package Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PACKAGE_NAME = 0;

  /**
   * The feature id for the '<em><b>Packages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PACKAGES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.PackageDefinitionImpl <em>Package Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.PackageDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getPackageDefinition()
   * @generated
   */
  int PACKAGE_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DEFINITION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Package Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DEFINITION__PACKAGE_NAME = 1;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DEFINITION__CLASSES = 2;

  /**
   * The number of structural features of the '<em>Package Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.ClassDefinitionImpl <em>Class Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.ClassDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getClassDefinition()
   * @generated
   */
  int CLASS_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DEFINITION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DEFINITION__NAME = 1;

  /**
   * The feature id for the '<em><b>Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DEFINITION__MEMBERS = 2;

  /**
   * The number of structural features of the '<em>Class Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.MemberDefinitionImpl <em>Member Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.MemberDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getMemberDefinition()
   * @generated
   */
  int MEMBER_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_DEFINITION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_DEFINITION__METHOD = 1;

  /**
   * The feature id for the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_DEFINITION__PROPERTY = 2;

  /**
   * The number of structural features of the '<em>Member Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.MethodDefinitionImpl <em>Method Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.MethodDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getMethodDefinition()
   * @generated
   */
  int METHOD_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION__VISIBILITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION__NAME = 2;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION__PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION__RETURN_TYPE = 4;

  /**
   * The number of structural features of the '<em>Method Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEFINITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.PropertyDefinitionImpl <em>Property Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.PropertyDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getPropertyDefinition()
   * @generated
   */
  int PROPERTY_DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__ANNOTATIONS = 0;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__VISIBILITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__NAME = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__TYPE = 3;

  /**
   * The feature id for the '<em><b>Default Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__DEFAULT_VALUE = 4;

  /**
   * The number of structural features of the '<em>Property Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.ParameterDefinitionImpl <em>Parameter Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.ParameterDefinitionImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getParameterDefinition()
   * @generated
   */
  int PARAMETER_DEFINITION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__TYPE = 1;

  /**
   * The feature id for the '<em><b>Default Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__DEFAULT_VALUE = 2;

  /**
   * The number of structural features of the '<em>Parameter Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.AnnotationImpl <em>Annotation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.AnnotationImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getAnnotation()
   * @generated
   */
  int ANNOTATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION__ARGUMENTS = 1;

  /**
   * The number of structural features of the '<em>Annotation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link springboot.automate.grabDsl.impl.AnnotationArgumentImpl <em>Annotation Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see springboot.automate.grabDsl.impl.AnnotationArgumentImpl
   * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getAnnotationArgument()
   * @generated
   */
  int ANNOTATION_ARGUMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION_ARGUMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION_ARGUMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Annotation Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION_ARGUMENT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see springboot.automate.grabDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.Model#getPackageName <em>Package Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package Name</em>'.
   * @see springboot.automate.grabDsl.Model#getPackageName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_PackageName();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.Model#getPackages <em>Packages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Packages</em>'.
   * @see springboot.automate.grabDsl.Model#getPackages()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Packages();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.PackageDefinition <em>Package Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Definition</em>'.
   * @see springboot.automate.grabDsl.PackageDefinition
   * @generated
   */
  EClass getPackageDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.PackageDefinition#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see springboot.automate.grabDsl.PackageDefinition#getAnnotations()
   * @see #getPackageDefinition()
   * @generated
   */
  EReference getPackageDefinition_Annotations();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.PackageDefinition#getPackageName <em>Package Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package Name</em>'.
   * @see springboot.automate.grabDsl.PackageDefinition#getPackageName()
   * @see #getPackageDefinition()
   * @generated
   */
  EAttribute getPackageDefinition_PackageName();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.PackageDefinition#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see springboot.automate.grabDsl.PackageDefinition#getClasses()
   * @see #getPackageDefinition()
   * @generated
   */
  EReference getPackageDefinition_Classes();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.ClassDefinition <em>Class Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Definition</em>'.
   * @see springboot.automate.grabDsl.ClassDefinition
   * @generated
   */
  EClass getClassDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.ClassDefinition#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see springboot.automate.grabDsl.ClassDefinition#getAnnotations()
   * @see #getClassDefinition()
   * @generated
   */
  EReference getClassDefinition_Annotations();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.ClassDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.ClassDefinition#getName()
   * @see #getClassDefinition()
   * @generated
   */
  EAttribute getClassDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.ClassDefinition#getMembers <em>Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Members</em>'.
   * @see springboot.automate.grabDsl.ClassDefinition#getMembers()
   * @see #getClassDefinition()
   * @generated
   */
  EReference getClassDefinition_Members();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.MemberDefinition <em>Member Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member Definition</em>'.
   * @see springboot.automate.grabDsl.MemberDefinition
   * @generated
   */
  EClass getMemberDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.MemberDefinition#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see springboot.automate.grabDsl.MemberDefinition#getAnnotations()
   * @see #getMemberDefinition()
   * @generated
   */
  EReference getMemberDefinition_Annotations();

  /**
   * Returns the meta object for the containment reference '{@link springboot.automate.grabDsl.MemberDefinition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see springboot.automate.grabDsl.MemberDefinition#getMethod()
   * @see #getMemberDefinition()
   * @generated
   */
  EReference getMemberDefinition_Method();

  /**
   * Returns the meta object for the containment reference '{@link springboot.automate.grabDsl.MemberDefinition#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property</em>'.
   * @see springboot.automate.grabDsl.MemberDefinition#getProperty()
   * @see #getMemberDefinition()
   * @generated
   */
  EReference getMemberDefinition_Property();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.MethodDefinition <em>Method Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Definition</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition
   * @generated
   */
  EClass getMethodDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.MethodDefinition#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition#getAnnotations()
   * @see #getMethodDefinition()
   * @generated
   */
  EReference getMethodDefinition_Annotations();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.MethodDefinition#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition#getVisibility()
   * @see #getMethodDefinition()
   * @generated
   */
  EAttribute getMethodDefinition_Visibility();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.MethodDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition#getName()
   * @see #getMethodDefinition()
   * @generated
   */
  EAttribute getMethodDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.MethodDefinition#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition#getParameters()
   * @see #getMethodDefinition()
   * @generated
   */
  EReference getMethodDefinition_Parameters();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.MethodDefinition#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Return Type</em>'.
   * @see springboot.automate.grabDsl.MethodDefinition#getReturnType()
   * @see #getMethodDefinition()
   * @generated
   */
  EAttribute getMethodDefinition_ReturnType();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.PropertyDefinition <em>Property Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Definition</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition
   * @generated
   */
  EClass getPropertyDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.PropertyDefinition#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition#getAnnotations()
   * @see #getPropertyDefinition()
   * @generated
   */
  EReference getPropertyDefinition_Annotations();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.PropertyDefinition#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition#getVisibility()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_Visibility();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.PropertyDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition#getName()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.PropertyDefinition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition#getType()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_Type();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.PropertyDefinition#getDefaultValue <em>Default Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default Value</em>'.
   * @see springboot.automate.grabDsl.PropertyDefinition#getDefaultValue()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_DefaultValue();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.ParameterDefinition <em>Parameter Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Definition</em>'.
   * @see springboot.automate.grabDsl.ParameterDefinition
   * @generated
   */
  EClass getParameterDefinition();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.ParameterDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.ParameterDefinition#getName()
   * @see #getParameterDefinition()
   * @generated
   */
  EAttribute getParameterDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.ParameterDefinition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see springboot.automate.grabDsl.ParameterDefinition#getType()
   * @see #getParameterDefinition()
   * @generated
   */
  EAttribute getParameterDefinition_Type();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.ParameterDefinition#getDefaultValue <em>Default Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default Value</em>'.
   * @see springboot.automate.grabDsl.ParameterDefinition#getDefaultValue()
   * @see #getParameterDefinition()
   * @generated
   */
  EAttribute getParameterDefinition_DefaultValue();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.Annotation <em>Annotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Annotation</em>'.
   * @see springboot.automate.grabDsl.Annotation
   * @generated
   */
  EClass getAnnotation();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.Annotation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.Annotation#getName()
   * @see #getAnnotation()
   * @generated
   */
  EAttribute getAnnotation_Name();

  /**
   * Returns the meta object for the containment reference list '{@link springboot.automate.grabDsl.Annotation#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arguments</em>'.
   * @see springboot.automate.grabDsl.Annotation#getArguments()
   * @see #getAnnotation()
   * @generated
   */
  EReference getAnnotation_Arguments();

  /**
   * Returns the meta object for class '{@link springboot.automate.grabDsl.AnnotationArgument <em>Annotation Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Annotation Argument</em>'.
   * @see springboot.automate.grabDsl.AnnotationArgument
   * @generated
   */
  EClass getAnnotationArgument();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.AnnotationArgument#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see springboot.automate.grabDsl.AnnotationArgument#getName()
   * @see #getAnnotationArgument()
   * @generated
   */
  EAttribute getAnnotationArgument_Name();

  /**
   * Returns the meta object for the attribute '{@link springboot.automate.grabDsl.AnnotationArgument#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see springboot.automate.grabDsl.AnnotationArgument#getValue()
   * @see #getAnnotationArgument()
   * @generated
   */
  EAttribute getAnnotationArgument_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GrabDslFactory getGrabDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.ModelImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Package Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__PACKAGE_NAME = eINSTANCE.getModel_PackageName();

    /**
     * The meta object literal for the '<em><b>Packages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PACKAGES = eINSTANCE.getModel_Packages();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.PackageDefinitionImpl <em>Package Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.PackageDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getPackageDefinition()
     * @generated
     */
    EClass PACKAGE_DEFINITION = eINSTANCE.getPackageDefinition();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DEFINITION__ANNOTATIONS = eINSTANCE.getPackageDefinition_Annotations();

    /**
     * The meta object literal for the '<em><b>Package Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DEFINITION__PACKAGE_NAME = eINSTANCE.getPackageDefinition_PackageName();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DEFINITION__CLASSES = eINSTANCE.getPackageDefinition_Classes();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.ClassDefinitionImpl <em>Class Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.ClassDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getClassDefinition()
     * @generated
     */
    EClass CLASS_DEFINITION = eINSTANCE.getClassDefinition();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DEFINITION__ANNOTATIONS = eINSTANCE.getClassDefinition_Annotations();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_DEFINITION__NAME = eINSTANCE.getClassDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DEFINITION__MEMBERS = eINSTANCE.getClassDefinition_Members();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.MemberDefinitionImpl <em>Member Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.MemberDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getMemberDefinition()
     * @generated
     */
    EClass MEMBER_DEFINITION = eINSTANCE.getMemberDefinition();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_DEFINITION__ANNOTATIONS = eINSTANCE.getMemberDefinition_Annotations();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_DEFINITION__METHOD = eINSTANCE.getMemberDefinition_Method();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_DEFINITION__PROPERTY = eINSTANCE.getMemberDefinition_Property();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.MethodDefinitionImpl <em>Method Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.MethodDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getMethodDefinition()
     * @generated
     */
    EClass METHOD_DEFINITION = eINSTANCE.getMethodDefinition();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DEFINITION__ANNOTATIONS = eINSTANCE.getMethodDefinition_Annotations();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DEFINITION__VISIBILITY = eINSTANCE.getMethodDefinition_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DEFINITION__NAME = eINSTANCE.getMethodDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_DEFINITION__PARAMETERS = eINSTANCE.getMethodDefinition_Parameters();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DEFINITION__RETURN_TYPE = eINSTANCE.getMethodDefinition_ReturnType();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.PropertyDefinitionImpl <em>Property Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.PropertyDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getPropertyDefinition()
     * @generated
     */
    EClass PROPERTY_DEFINITION = eINSTANCE.getPropertyDefinition();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_DEFINITION__ANNOTATIONS = eINSTANCE.getPropertyDefinition_Annotations();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__VISIBILITY = eINSTANCE.getPropertyDefinition_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__NAME = eINSTANCE.getPropertyDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__TYPE = eINSTANCE.getPropertyDefinition_Type();

    /**
     * The meta object literal for the '<em><b>Default Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__DEFAULT_VALUE = eINSTANCE.getPropertyDefinition_DefaultValue();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.ParameterDefinitionImpl <em>Parameter Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.ParameterDefinitionImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getParameterDefinition()
     * @generated
     */
    EClass PARAMETER_DEFINITION = eINSTANCE.getParameterDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DEFINITION__NAME = eINSTANCE.getParameterDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DEFINITION__TYPE = eINSTANCE.getParameterDefinition_Type();

    /**
     * The meta object literal for the '<em><b>Default Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DEFINITION__DEFAULT_VALUE = eINSTANCE.getParameterDefinition_DefaultValue();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.AnnotationImpl <em>Annotation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.AnnotationImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getAnnotation()
     * @generated
     */
    EClass ANNOTATION = eINSTANCE.getAnnotation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANNOTATION__NAME = eINSTANCE.getAnnotation_Name();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOTATION__ARGUMENTS = eINSTANCE.getAnnotation_Arguments();

    /**
     * The meta object literal for the '{@link springboot.automate.grabDsl.impl.AnnotationArgumentImpl <em>Annotation Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see springboot.automate.grabDsl.impl.AnnotationArgumentImpl
     * @see springboot.automate.grabDsl.impl.GrabDslPackageImpl#getAnnotationArgument()
     * @generated
     */
    EClass ANNOTATION_ARGUMENT = eINSTANCE.getAnnotationArgument();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANNOTATION_ARGUMENT__NAME = eINSTANCE.getAnnotationArgument_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANNOTATION_ARGUMENT__VALUE = eINSTANCE.getAnnotationArgument_Value();

  }

} //GrabDslPackage
