/**
 * generated by Xtext 2.32.0
 */
package springboot.automate.grabDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pom Xml</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getGroupId <em>Group Id</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getArtifactId <em>Artifact Id</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getVersion <em>Version</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getPackaging <em>Packaging</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getProperties <em>Properties</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.PomXml#getBuild <em>Build</em>}</li>
 * </ul>
 *
 * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml()
 * @model
 * @generated
 */
public interface PomXml extends EObject
{
  /**
   * Returns the value of the '<em><b>Group Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group Id</em>' attribute.
   * @see #setGroupId(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_GroupId()
   * @model
   * @generated
   */
  String getGroupId();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getGroupId <em>Group Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group Id</em>' attribute.
   * @see #getGroupId()
   * @generated
   */
  void setGroupId(String value);

  /**
   * Returns the value of the '<em><b>Artifact Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact Id</em>' attribute.
   * @see #setArtifactId(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_ArtifactId()
   * @model
   * @generated
   */
  String getArtifactId();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getArtifactId <em>Artifact Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact Id</em>' attribute.
   * @see #getArtifactId()
   * @generated
   */
  void setArtifactId(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Packaging</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packaging</em>' attribute.
   * @see #setPackaging(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_Packaging()
   * @model
   * @generated
   */
  String getPackaging();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getPackaging <em>Packaging</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Packaging</em>' attribute.
   * @see #getPackaging()
   * @generated
   */
  void setPackaging(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference.
   * @see #setProperties(Properties)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_Properties()
   * @model containment="true"
   * @generated
   */
  Properties getProperties();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getProperties <em>Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Properties</em>' containment reference.
   * @see #getProperties()
   * @generated
   */
  void setProperties(Properties value);

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference.
   * @see #setDependencies(Dependencies)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_Dependencies()
   * @model containment="true"
   * @generated
   */
  Dependencies getDependencies();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getDependencies <em>Dependencies</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependencies</em>' containment reference.
   * @see #getDependencies()
   * @generated
   */
  void setDependencies(Dependencies value);

  /**
   * Returns the value of the '<em><b>Build</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Build</em>' containment reference.
   * @see #setBuild(Build)
   * @see springboot.automate.grabDsl.GrabDslPackage#getPomXml_Build()
   * @model containment="true"
   * @generated
   */
  Build getBuild();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.PomXml#getBuild <em>Build</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Build</em>' containment reference.
   * @see #getBuild()
   * @generated
   */
  void setBuild(Build value);

} // PomXml
