/**
 * generated by Xtext 2.32.0
 */
package springboot.automate.grabDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link springboot.automate.grabDsl.Properties#getJavaVersion <em>Java Version</em>}</li>
 *   <li>{@link springboot.automate.grabDsl.Properties#getSpringBootVersion <em>Spring Boot Version</em>}</li>
 * </ul>
 *
 * @see springboot.automate.grabDsl.GrabDslPackage#getProperties()
 * @model
 * @generated
 */
public interface Properties extends EObject
{
  /**
   * Returns the value of the '<em><b>Java Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Version</em>' attribute.
   * @see #setJavaVersion(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getProperties_JavaVersion()
   * @model
   * @generated
   */
  String getJavaVersion();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.Properties#getJavaVersion <em>Java Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Version</em>' attribute.
   * @see #getJavaVersion()
   * @generated
   */
  void setJavaVersion(String value);

  /**
   * Returns the value of the '<em><b>Spring Boot Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spring Boot Version</em>' attribute.
   * @see #setSpringBootVersion(String)
   * @see springboot.automate.grabDsl.GrabDslPackage#getProperties_SpringBootVersion()
   * @model
   * @generated
   */
  String getSpringBootVersion();

  /**
   * Sets the value of the '{@link springboot.automate.grabDsl.Properties#getSpringBootVersion <em>Spring Boot Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spring Boot Version</em>' attribute.
   * @see #getSpringBootVersion()
   * @generated
   */
  void setSpringBootVersion(String value);

} // Properties
