/*
 * generated by Xtext 2.32.0
 */
package springboot.automate.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link GrabDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractGrabDslWebModule extends DefaultWebModule {

}
