/*
 * generated by Xtext 2.32.0
 */
package springboot.automate.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import springboot.automate.parser.antlr.internal.InternalGrabDslParser;
import springboot.automate.services.GrabDslGrammarAccess;

public class GrabDslParser extends AbstractAntlrParser {

	@Inject
	private GrabDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGrabDslParser createParser(XtextTokenStream stream) {
		return new InternalGrabDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GrabDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GrabDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
