/*
 * generated by Xtext 2.32.0
 */
package springboot.automate.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import springboot.automate.grabDsl.Model

@ExtendWith(InjectionExtension)
@InjectWith(GrabDslInjectorProvider)
class GrabDslParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	@Deprecated
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
